defaults:
  - _self_
  - datasets: simple


hydra:
  run:
    dir: ../experiments/${name}
  sweep:
    dir: ../experiments/${name}
  job:
    name: ${name}
    chdir: true

wandb:
  project: hydra-explore

seed: 1234